apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-maven
  labels:
    app: springboot-maven
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springboot-docker
  template:
    metadata:
      labels:
        app: springboot-docker
    spec:
      containers:
name: springboot-docker
          image: trialtq34vm.jfrog.io/springboot-docker/master:7d5bb9b7fd5cf0872f0aea427ee80131fedd0984
   ports:
containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: springboot-docker-service
spec:
  selector:
    app: springboot-maven
  ports:
protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
